name: Purge jsDelivr CDN

# Trigger workflow on push to main branch (or any branch you like)
on:
  push:
    branches:
      - main

jobs:
  purge:
    name: Purge jsDelivr Cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Purge jsDelivr CDN
        run: |
          # Set your repo details
          USERNAME="neelix2017"
          REPO="samsung-test"
          BRANCH="main"

          # Purge entire branch
          URL="https://purge.jsdelivr.net/gh/$USERNAME/$REPO@$BRANCH"

          echo "Purging jsDelivr cache for $URL"
          RESPONSE=$(curl -s -X GET "$URL")
          echo "Response: $RESPONSE"
